[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = ''

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# block some countries
[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["CU","IR","KP","SD","SY"]}
  headers = {Link="<https://vote.pooltogether.com>"}
